// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPKvwXKMRiagic3qCtqlOKZdFIqbtVNPI',
    appId: '1:496534288133:web:4091cb7471af641a52a96c',
    messagingSenderId: '496534288133',
    projectId: 'loreweaver-736ac',
    authDomain: 'loreweaver-736ac.firebaseapp.com',
    storageBucket: 'loreweaver-736ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-a-mdivPJ4AYBJSdKMp68HO1C9O4_Pqo',
    appId: '1:496534288133:android:76db511c4aedb93e52a96c',
    messagingSenderId: '496534288133',
    projectId: 'loreweaver-736ac',
    storageBucket: 'loreweaver-736ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvwiXYddP6JhxBOGbbrxvshCw3sQxVPyU',
    appId: '1:496534288133:ios:304a4a6ae11f672752a96c',
    messagingSenderId: '496534288133',
    projectId: 'loreweaver-736ac',
    storageBucket: 'loreweaver-736ac.firebasestorage.app',
    iosBundleId: 'com.example.loreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvwiXYddP6JhxBOGbbrxvshCw3sQxVPyU',
    appId: '1:496534288133:ios:366e508ccc8b90fe52a96c',
    messagingSenderId: '496534288133',
    projectId: 'loreweaver-736ac',
    storageBucket: 'loreweaver-736ac.firebasestorage.app',
    iosBundleId: 'com.franciscobarrera.lore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPKvwXKMRiagic3qCtqlOKZdFIqbtVNPI',
    appId: '1:496534288133:web:e0c34fdbc2dda22852a96c',
    messagingSenderId: '496534288133',
    projectId: 'loreweaver-736ac',
    authDomain: 'loreweaver-736ac.firebaseapp.com',
    storageBucket: 'loreweaver-736ac.firebasestorage.app',
  );
}
